# Generated by Django 4.2.16 on 2024-10-26 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=31, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)])),
                ('status', models.JSONField(default=[0])),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calender_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
